service: minecraft

provider:
  apiGateway:
    shouldStartNameWithService: true
  deploymentBucket:
    name: glyphrider-serverless-deployment
  name: aws
  region: ${opt:region, 'us-east-2'}

custom:
  stage: ${opt:stage}

functions:
  whitelist:
    events:
      - http:
          cors: true
          method: post
          path: whitelist
          private: false
    handler: whitelist.handler
    name: ${self:service}-${self:custom.stage}-whitelist
    role: minecraftRole
    runtime: nodejs12.x
  ops:
    events:
      - http:
          cors: true
          method: post
          path: ops
          private: false
    handler: ops.handler
    name: ${self:service}-${self:custom.stage}-ops
    role: minecraftRole
    runtime: nodejs12.x
resources:
  - ${file(resources/iam.yml)}

