version: 2.1
orbs:
  node: circleci/node@4.1.0
jobs:
  test:
    executor:
      name: node/default
    parameters:
      version: "12.20.0"
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: node --version
          name: Check node version
      - run:
          command: yarn run jest --coverage
          name: Run YARN tests
workflows:
  standard:
    jobs:
      - test
