version: 2.1
orbs:
  node: circleci/node@4.1.0
jobs:
  test:
    executor:
      name: node/default
      tag: 12.20
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - node/test:
          pkg-manager: yarn
workflows:
  standard:
    jobs:
      - test
